apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ryanbeales-com

resources:
  - deployment.yaml

configMapGenerator:
  - name: email-forwarder-script
    files:
      - forwarder.py
