apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: mqtt
    app.kubernetes.io/name: mosquitto
  name: mosquitto
  namespace: mosquitto
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: mosquitto
      app.kubernetes.io/name: mosquitto
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: mosquitto
        app.kubernetes.io/name: mosquitto
    spec:
      initContainers:
        - name: fix-permissions
          image: alpine:3.18
          command:
            [
              "sh",
              "-c",
              "cp /tmp/config/* /mosquitto/config/ && chown -R 1883:1883 /mosquitto/config/ && chmod 0700 /mosquitto/config/accounts.conf",
            ]
          volumeMounts:
            - mountPath: /tmp/config
              name: config-volume
            - mountPath: /mosquitto/config
              name: config-volume-writable
      containers:
        # https://hub.docker.com/_/eclipse-mosquitto/tags
        - image: eclipse-mosquitto:2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - mosquitto_sub
                - -h
                - 127.0.0.1
                - -p
                - "1884"
                - -t
                - "$SYS/broker/uptime"
                - -C
                - "1"
            tcpSocket: null
            initialDelaySeconds: 5
            periodSeconds: 20
            timeoutSeconds: 5
          name: mosquitto
          ports:
            - containerPort: 1883
              name: mqtt
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - mosquitto_sub
                - -h
                - 127.0.0.1
                - -p
                - "1884"
                - -t
                - "$SYS/broker/uptime"
                - -C
                - "1"
            tcpSocket: null
            initialDelaySeconds: 5
            periodSeconds: 20
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /mosquitto/config
              name: config-volume-writable
            - mountPath: /mosquitto/data/
              name: mosquitto-data
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: mosquitto
          name: config-volume
        - emptyDir: {}
          name: config-volume-writable
        - emptyDir: {}
          name: mosquitto-data
