apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mosquitto
resources:
  - ./namespace.yaml
  - ./service.yaml
  - ./service-external.yaml
  - ./deployment.yaml
  - ./config.yaml
