apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: envoy-gateway-system
helmCharts:
  - name: gateway-helm
    repo: oci://docker.io/envoyproxy/
    # https://github.com/envoyproxy/gateway/releases
    version: 1.6.2
    releaseName: envoy-gateway
    namespace: envoy-gateway-system
    valuesFile: values.yaml
    includeCRDs: true
resources:
  - namespace.yaml
  - gatewayclass.yaml
  - pod-monitor-controller.yaml
  - pod-monitor-proxies.yaml

configMapGenerator:
  - name: envoy-gateway-dashboards
    files:
      - envoy-gateway-global.json
      - envoy-proxy-global.json
    options:
      labels:
        grafana_dashboard: "1"
