resources:
  - namespace.yaml
  - dns/croblodocus-direct.yaml
  - dns/croblodocus-wildcard.yaml
  - dns/croblociraptor-direct.yaml
  - dns/croblociraptor-wildcard.yaml
  - dns/crobasaurusrex-direct.yaml
  - dns/crobasaurusrex-wildcard.yaml
  - dns/crobceretops-direct.yaml
  - dns/crobceretops-wildcard.yaml
  - dns/aws-acm-validation.yaml
  - dns/aws-acm-validation-apex.yaml
  - dns/blog.ryanbeales.com.yaml
  - dns/blog.ryanbeales.com-validation.yaml
  - dns/www.ryanbeales.com.yaml
  - dns/apex-domain.yaml
  - cloudfront/distribution.yaml
  - acm/certificate.yaml
  - s3/bucket.yaml
  - s3/bucket-policy.yaml
  - s3/mx-bucket.yaml
  - s3/mx-bucket-policy.yaml
  - sync/iam-user.yaml
  - sync/iam-access-key.yaml
  - sync/iam-policy.yaml
  - sync/iam-policy-attachment.yaml
  - sync/cronjob.yaml
  - ses/domain-identity.yaml
  - ses/dkim.yaml
  - ses/receipt-rule-set.yaml
  - ses/receipt-rule.yaml
  - dns/ses-mx.yaml
  - dns/ses-spf.yaml
  - dns/ses-verification.yaml
  - dns/ses-dkim.yaml
  - dns/ses-dmarc.yaml
